## Final Project Milestone 1

Now I am thinking of the primary question I am trying to ask - How have the H1B data trends changed over the years. What states? What industries? The focus of the dashboard is going to be from the perspective of an International student looking for a job in the United States

I am going to start working primarily with H1B data that is publicly available on the USCIS website. I will have to download multiple files as the data from 2020 - 2025 consists of approximately 3,22,000 rows.

I also found the wage data through LCA (Labor Condition Application) on the Department of Labor website. The data is divided into quarters for each year. I will have to download all the data from 2020 to 2025 and integrate them with the H1B data. Can I just work on 2025 wage data and use just that year's H1b data for the wage insights?

In [1]:
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
H1b = pd.read_csv("Employer Information.csv")
H1b.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

In [ ]:
H1b = pd.read_csv("Employer Information.csv", encoding = "utf-16")
h1b.head()

ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 3

In [ ]:
H1b = pd.read_csv("Employer Information.csv", encoding = "utf=16", sep = "delimiter", header = None)
H1b.head()

C:\Users\anana\AppData\Local\Temp\ipykernel_13100\3221571586.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  H1b = pd.read_csv("Employer Information.csv", encoding = "utf=16", sep = "delimiter", header = None)

                                                   0
0  Line by line\tFiscal Year   \tEmployer (Petiti...
1  1\t2026\t\t4902\t31-33 - Manufacturing\tRANDOL...
2  2\t2026\t\t9012\t31-33 - Manufacturing\tHILLSB...
3  3\t2026\t1 EMC LLC\t9142\t72 - Accommodation a...
4  4\t2026\t1 NET SOFTWARE TECHNOLOGIES\t9485\t54...

In [14]:
H1b = pd.read_csv("Employer Information.csv", encoding = "utf-16", sep="\t")
#the csv file is not encoded as standard utf-8 so we specify utf-16, additionally the sep = "\t" correctly separates the columns using tab rather than comma. 
# Reference : https://stackoverflow.com/questions/18039057/pandas-parser-cparsererror-error-tokenizing-data
H1b.head()

C:\Users\anana\AppData\Local\Temp\ipykernel_35648\1400217045.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  H1b = pd.read_csv("Employer Information.csv", encoding = "utf-16", sep="\t")

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2023,NaN,NaN,NaN,FAIRFIELD,IA,52556.0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,2023,NaN,8070.0,51 - Information,WILMINGTON,DE,19801.0,1,0,0,0,0,0,0,0,0,0,0,0
2,3,2023,NaN,8424.0,"54 - Professional, Scientific, and Technical S...",BROOKLYN,NY,11220.0,0,0,1,0,0,0,0,0,0,0,0,0
3,4,2023,NaN,8435.0,52 - Finance and Insurance,NEW YORK,NY,10017.0,0,0,1,0,0,0,0,0,0,0,0,0
4,5,2023,1 800 CONTACTS INC,1643.0,42 - Wholesale Trade,DRAPER,UT,84020.0,0,0,0,0,0,0,0,0,2,0,0,0

Is it better to integrate 2-3 data sets for the dashboard? Or is it going to be more efficient to just work on the USCIS dataset

In [4]:
H1b.columns

Index(['Line by line', 'Fiscal Year   ', 'Employer (Petitioner) Name',
       'Tax ID', 'Industry (NAICS) Code', 'Petitioner City',
       'Petitioner State', 'Petitioner Zip Code', 'New Employment Approval',
       'New Employment Denial', 'Continuation Approval', 'Continuation Denial',
       'Change with Same Employer Approval',
       'Change with Same Employer Denial', 'New Concurrent Approval',
       'New Concurrent Denial', 'Change of Employer Approval',
       'Change of Employer Denial', 'Amended Approval', 'Amended Denial'],
      dtype='object')

In [5]:
type(H1b["Fiscal Year   "].iloc[0])

numpy.int64

In [ ]:
H1b.rename(columns={"Fiscal Year   ": "Fiscal Year"}, inplace=True)
# I changed the column name as it had extra characters for space which could have led to errors later on.
# Source - https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html

In [11]:
len(H1b["Fiscal Year"])

173285

In [7]:
H1b_2 = pd.read_csv("Employer Information 2.csv", encoding = "utf-16", sep="\t")
H1b_2.head()

C:\Users\anana\AppData\Local\Temp\ipykernel_35648\3273105424.py:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  H1b_2 = pd.read_csv("Employer Information 2.csv", encoding = "utf-16", sep="\t")

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,0,0,0,0,0,0,0,0,0
1,2,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,0,0,0,0,0,0,0,0,0
3,4,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,0,0,0,0,0,0,0,0,0

In [ ]:
H1b_2.rename(columns={"Fiscal Year   ": "Fiscal Year"}, inplace=True)
# Similarly I changed the column name for this file as well.

In [13]:
len(H1b_2["Fiscal Year"])

148510

1. For this milestone, I have finalised working on the H1B data from USCIS data hub and build a more insight dashboard as opposed to the basic search dashboard that is available on the USCIS website. 
2. I have narrowed my audience to International student population graduating in 2026 and looking for a job for whom this information will provide insights like what have been the H1b trends over the last 6 years? Which industries have had the highest H1b approvals? Which region in the United States has seen the highest H1b activity?
3. These insights will help international students do a more targeted job search.
4. For this milestone, I have also created the data frame of both files. Moving forward I will be working on 2 files. I have understood that this file does not follow the standard utf-8 encoding so I need to encode it as utf-16 and also use Sep = \t feature to correctly create the data frame.
5. I also started playing around with the data frames to try to understand. I changed the column names to remove the excess space which could have resulted in errors later on. I will be working a lot with the Fiscal Year variable as I am looking to see H1b trends over the past 6 years. The data also follows tidy data principles so I will not need to clean it too much. For the next milestone, I can start by creating basic charts to understand the data better and then build on it.