In [71]:
import pandas as pd
from matplotlib import pyplot as plt
import plotly.graph_objects as go # or plotly.express as px
from plotly.subplots import make_subplots
import numpy as np
from urllib.request import urlopen
import json

In [72]:
H1b = pd.read_csv("Employer Information.csv", encoding = "utf=16", sep = "\t")
H1b.head()

C:\Users\anana\AppData\Local\Temp\ipykernel_29144\3666231126.py:1: DtypeWarning:

Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2023,NaN,NaN,NaN,FAIRFIELD,IA,52556.0,0,1,0,0,0,0,0,0,0,0,0,0
1,2,2023,NaN,8070.0,51 - Information,WILMINGTON,DE,19801.0,1,0,0,0,0,0,0,0,0,0,0,0
2,3,2023,NaN,8424.0,"54 - Professional, Scientific, and Technical S...",BROOKLYN,NY,11220.0,0,0,1,0,0,0,0,0,0,0,0,0
3,4,2023,NaN,8435.0,52 - Finance and Insurance,NEW YORK,NY,10017.0,0,0,1,0,0,0,0,0,0,0,0,0
4,5,2023,1 800 CONTACTS INC,1643.0,42 - Wholesale Trade,DRAPER,UT,84020.0,0,0,0,0,0,0,0,0,2,0,0,0

In [73]:
H1b_2 = pd.read_csv("Employer Information 2.csv", encoding = "utf-16", sep="\t")
H1b_2.tail()

C:\Users\anana\AppData\Local\Temp\ipykernel_29144\843306738.py:1: DtypeWarning:

Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
148505,"148,506",2024,ZYNO MEDICAL LLC,7390.0,31-33 - Manufacturing,NATICK,MA,1760.0,0,0,0,0,0,0,0,0,0,0,2,0
148506,"148,507",2024,ZYON DIGITAL SOLUTIONS LLC,3124.0,"54 - Professional, Scientific, and Technical S...",EL PASO,TX,79911.0,1,0,0,0,0,0,0,0,2,0,0,0
148507,"148,508",2024,ZYSCOVICH LLC,4852.0,"54 - Professional, Scientific, and Technical S...",MIAMI,FL,33132.0,1,0,0,0,0,0,0,0,0,0,0,0
148508,"148,509",2024,ZYTUS INC,96.0,"54 - Professional, Scientific, and Technical S...",RICHMOND,VA,23238.0,2,0,0,0,0,0,0,0,0,0,0,0
148509,"148,510",2024,ZYWIE INC,9321.0,"54 - Professional, Scientific, and Technical S...",JOHNS CREEK,GA,30097.0,0,0,1,0,0,0,0,0,0,0,0,0

In [74]:
H1b_comp = pd.concat([H1b_2, H1b], ignore_index= True)
H1b_comp.head()

,Line by line,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial
0,1,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,0,0,0,0,0,0,0,0,0
1,2,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,0,0,0,0,0,0,0,0,0
2,3,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,0,0,0,0,0,0,0,0,0
3,4,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,0,0,0,0,0,0,0,1,0
4,5,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,0,0,0,0,0,0,0,0,0

In [75]:
H1b_comp = H1b_comp.drop(columns=["Line by line"])

In [76]:
H1b_comp.columns = H1b_comp.columns.str.strip()

In [77]:
State_map = {"AL" : "Alabama",
"AK" : "Alaska",
"AZ" : "Arizona",
"AR" : "Arkansas",
"CA" : "California",
"CO" : "Colorado",
"CT" : "Connecticut",
"DE" : "Delaware",
"DC" : "District of Columbia",
"FL" : "Florida",
"GA" : "Georgia",
"HI" : "Hawaii",
"ID" : "Idaho",
"IL" : "Illinois",
"IN" : "Indiana",
"IA" : "Iowa",
"KS" : "Kansas",
"KY" : "Kentucky",
"LA" : "Louisiana",
"ME" : "Maine",
"MD" : "Maryland",
"MA" : "Massachusetts",
"MI" : "Michigan",
"MN" : "Minnesota",
"MS" : "Mississippi",
"MO" : "Missouri",
"MT" : "Montana",
"NE" : "Nebraska",
"NV" : "Nevada",
"NH" : "New Hampshire",
"NJ" : "New Jersey",
"NM" : "New Mexico",
"NY" : "New York",
"NC" : "North Carolina",
"ND" : "North Dakota",
"OH" : "Ohio",
"OK" : "Oklahoma",
"OR" : "Oregon",
"PA" : "Pennsylvania",
"RI" : "Rhode Island",
"SC" : "South Carolina",
"SD" : "South Dakota",
"TN" : "Tennessee",
"TX" : "Texas",
"UT" : "Utah",
"VT" : "Vermont",
"VA" : "Virginia",
"WA" : "Washington",
"WV" : "West Virginia",
"WI" : "Wisconsin",
"WY" : "Wyoming" }

In [78]:
state_counts = H1b_comp.groupby("Petitioner State").count()['Employer (Petitioner) Name']
#state_counts_top10 = state_counts.nlargest(10)

fig1 = go.Figure(go.Choropleth(
    locations = state_counts.index,
    z = state_counts.values,
    text=state_counts.index.map(State_map),
    locationmode = "USA-states",
    colorscale = "Blues",
    colorbar_title = "H1B Petitions",
    hovertemplate="<b>%{text}</b><br>Petitions: %{z:,}<extra></extra>"
))

fig1.update_geos(
    visible = False, resolution = 110, scope = "usa",
    showcountries = True, countrycolor = "Black",
    showsubunits = True, 
    subunitcolor = "Black"
)

fig1.update_layout(
    title = "H1B Petitions by State (2021-2025)",
    height = 500,
    margin = {"r": 0, "t" : 50, "l" : 10, "b" : 50}
)

fig1.show()

# Source - https://claude.ai/chat/50981cae-65c2-43af-84f6-fcadafb66e60

In [79]:
state_counts = H1b_comp.groupby("Petitioner State").count()['Employer (Petitioner) Name']
state_counts_top10 = state_counts.nlargest(10)
fig2 = go.Figure(
    data=[
    go.Pie(
        labels=state_counts_top10.index.map(State_map), 
        values=state_counts_top10.values,
        title="Petitioner States Percentage"
        )])

fig2.show()

pandas.DataFrame.replace

In [80]:
print(H1b_comp["Petitioner State"])

0         MA
1         NH
2         OH
3         TX
4         NY
          ..
321790    VA
321791    VA
321792    WI
321793    GA
321794    CA
Name: Petitioner State, Length: 321795, dtype: object

In [81]:
type(H1b_comp['Petitioner State'].iloc[0])

str

In [82]:
H1b_comp["State_CA&Other"] = np.where(H1b_comp["Petitioner State"] =="CA", "California", "Other")

In [83]:
H1b_comp.head()

,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,Continuation Denial,Change with Same Employer Approval,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial,State_CA&Other
0,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,0,0,0,0,0,0,0,0,0,Other
1,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,0,0,0,0,0,0,0,0,0,Other
2,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,0,0,0,0,0,0,0,0,0,Other
3,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,0,0,0,0,0,0,0,1,0,Other
4,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,0,0,0,0,0,0,0,0,0,Other

In [84]:
H1b_comp['NewEmpAppr_int'] = pd.to_numeric(H1b_comp['New Employment Approval'], errors='coerce')

In [85]:
Petitioner_State = H1b_comp.groupby("State_CA&Other")['NewEmpAppr_int'].sum()
Petitioner_State

State_CA&Other
California    102300.0
Other         480476.0
Name: NewEmpAppr_int, dtype: float64

In [86]:
fig3 = go.Figure(
    data=[
    go.Pie(
        labels=Petitioner_State.index, 
        values=Petitioner_State.values,
        title="Petitioner States Percentage - California & Otherss"
        )])

fig3.show()

In [87]:

state_newvisa_app = H1b_comp.groupby("Petitioner State")["NewEmpAppr_int"].sum()
state_newapprovals_top10 = state_newvisa_app.nlargest(10)
print(state_newapprovals_top10)

Petitioner State
CA    102300.0
TX     69249.0
NJ     54202.0
NY     53864.0
IL     29804.0
MA     27015.0
VA     24363.0
PA     19656.0
GA     18848.0
FL     18290.0
Name: NewEmpAppr_int, dtype: float64

In [100]:
State_Map2 = {
    'CA': 'California',
    'TX': 'Top10',
    'NY': 'Top10',
    'NJ': "Top10",
    'FL': 'Top10',
    'IL': 'Top10',
    'MA': 'Top10',
    'VA': 'Top10',
    'PA': 'Top10',
    'GA': 'Top10'
}

In [101]:
H1b_comp['Petitioner_state_Top10'] = H1b_comp['Petitioner State'].map(State_Map2).fillna('Others')

In [102]:
H1b_comp.head()

,Fiscal Year,Employer (Petitioner) Name,Tax ID,Industry (NAICS) Code,Petitioner City,Petitioner State,Petitioner Zip Code,New Employment Approval,New Employment Denial,Continuation Approval,...,Change with Same Employer Denial,New Concurrent Approval,New Concurrent Denial,Change of Employer Approval,Change of Employer Denial,Amended Approval,Amended Denial,State_CA&Other,NewEmpAppr_int,Petitioner_state_Top10
0,2026,NaN,4902.0,31-33 - Manufacturing,RANDOLPH,MA,2368.0,0,0,1,...,0,0,0,0,0,0,0,Other,0.0,Top10
1,2026,NaN,9012.0,31-33 - Manufacturing,HILLSBOROUGH,NH,3244.0,0,0,1,...,0,0,0,0,0,0,0,Other,0.0,Others
2,2026,1 EMC LLC,9142.0,72 - Accommodation and Food Services,FINDLAY,OH,45840.0,1,0,0,...,0,0,0,0,0,0,0,Other,1.0,Others
3,2026,1 NET SOFTWARE TECHNOLOGIES,9485.0,"54 - Professional, Scientific, and Technical S...",IRVING,TX,75063.0,0,0,0,...,0,0,0,0,0,1,0,Other,0.0,Top10
4,2026,1-800-FLOWERS COM INC,7311.0,44-45 - Retail Trade,JERICHO,NY,11753.0,0,0,1,...,0,0,0,0,0,0,0,Other,0.0,Top10

In [103]:
Petitioner_State_10 = H1b_comp.groupby("Petitioner_state_Top10")['NewEmpAppr_int'].sum()
Petitioner_State_10

Petitioner_state_Top10
California    102300.0
Others        165185.0
Top10         315291.0
Name: NewEmpAppr_int, dtype: float64

In [104]:
fig4 = go.Figure(
    data=[
    go.Pie(
        labels=Petitioner_State_10.index, 
        values=Petitioner_State_10.values,
        title="Petitioner States Percentage - Top 10 and Others"
        )])

fig4.show()